### ISSUE TITLE
Autocraft with macro chain "/nextmacro" command gives in game Dalamud Error

### ISSUE THREAD

**Issue by RenYuanXue** [hikarin-dev/Auto-Crafter#1]
I tried auto crafting + macro chain, I have /nextmacro at the end of the first macro.
I ran into error several times once the macro reached the very last action of the first macro.

Is there anything I miss in order for it to support extended macro with macro chain?

**Comment by hikarin-dev** [comment]
This trigger only process log lines and send keypresses, so it's probably how the macro is setup that is the problem.
Are you using <wait.3> before the /nextmacro line, and are your macros in the user macros window in sequential order?

For example:
Macro #10
```
/ac "Trained Eye" <wait.3>
/nextmacro
```
Macro #11
```
/ac Veneration <wait.2>
/nextmacro
```
Macro #12
```
/ac Groundwork
```

**Comment by RenYuanXue** [comment]
![image](https://user-images.githubusercontent.com/48230775/224783576-60e8931a-f28f-4f4d-b0f0-71d9f852e625.png)
![image](https://user-images.githubusercontent.com/48230775/224783664-13dc410b-1aaa-4d0a-ae6d-b51c77797780.png)

Yes, this is how I setup my macros, and 3 seconds after Trained Eye is used, I got error message:

![image](https://user-images.githubusercontent.com/48230775/224784056-31b9ffe4-f26e-490e-b0cc-658bc50039a7.png)

Edit: I'm using MacroChain v2.1.0.5 and autocraft v2.3.6. I tried using /nextmacro without autocraft and it works fine.

**Comment by hikarin-dev** [comment]
Took a while to reproduce, it appears to be a Macro Chain issue.

Telesto is sending a `/runmacro ## individual/shared` command, and a macro that is triggered using `/runmacro` cannot execute a `/nextmacro` command, or the game crashes, regardless if Telesto sends it or you type it in the chat log.

Instead of setting your initial macro using `/e ac macro [shared|individual] [0-99]` , you can drag your first macro to your hotbar with keybind num1 so that it's not called using `/runmacro`

Alternatively, since you're already using additional dependencies like Telesto, you can use [Something Needs Doing](https://raw.githubusercontent.com/daemitus/MyDalamudPlugins/master/pluginmaster.json) plugin instead to host your macros, (which is also my current setup). Main advantage is it replaces all keybinds with commands send by Telesto, so you can type and check some other stuff without interrupting your crafts. Instructions can be found [here](https://github.com/gynryiie/Auto-Crafter#with-act-and-dalamud-plugins), and requires the auto crafter v2.3.7 update.

There's also the [Artisan](https://love.puni.sh/ment.json) plugin, which could replace this entire trigger soon, the only advantage left from using this trigger is ease of use and maximizing your spiritbond output.

**Comment by RenYuanXue** [comment]
Thank you for the detailed instructions. I wanted to try Something Needs Doing +autocraft for a while now but didnt now how to install it (using the dalamud + json url gives me a error so I stopped).

I finished my tool enhancement using the first setup you mentioned.

Thank you again for making this trigger and maintaining it :D
