### ISSUE TITLE
[SND] addon not found

### ISSUE THREAD

**Issue by 3r022** [hikarin-dev/Auto-Crafter#5]
For some reason I am not able to get the SND addons to be recognised. The .json config is in the in the config folder and triggernometry is working. Any help appreciated :)

**Comment by hikarin-dev** [comment]
Do you have SomethingNeedsDoing and Telesto plugin installed?

**Comment by 3r022** [comment]
Yeah, I made sure the correct plugins are installed. I also have the sample macros available in SND, however no /waitaddon lines work saying the plugins are missing. I've checked with /xldata and they don't show there either. Telesto config indicates that is working aswell, so I'm completely stumped as to what is causing the /waitaddon addons to not work

**Comment by gynryiie** [comment]
I see, the term SomethingNeedDoing plugin is a bit confusing, the macro uses `/waitaddon "RecipeNote"`, `/waitaddon "Synthesis"` and for those lines to proceed, the Crafting Log Window, and Synthesis Window needs to be open respectively. So the addon is referring to a game UI that needs to be active/visible.

You can also verify if the connection between triggernometry and telesto to snd is properly configured if you see an echo message saying `where plogon` after you first enabled the auto crafter

**Comment by hikarin-dev** [comment]
I see, the term SomethingNeedDoing plugin is using is a bit confusing, the trigger uses `/waitaddon "RecipeNote"`, `/waitaddon "Synthesis"` and for those lines to proceed, the Crafting Log Window, and Synthesis Window needs to be open respectively. So the "addon" / "plugin" snd is referring to is the game UI that needs to be active/visible.

Also make sure you have selected the NQ/HQ items in the Crafting Log Window, for `/waitaddon "Synthesis"` to proceed properly

You can also verify if the connection between triggernometry and telesto to snd is properly configured if you see an echo message saying `where plogon` after you first enabled the auto crafter in game.

**Comment by 3r022** [comment]
I'm pretty sure I got it. Telesto changed their ports to 45678 somewhat recently. The triggernometry xml has 51323 hardcoded in. Ill change it quick and let you know if it works

**Comment by 3r022** [comment]
> I'm pretty sure I got it. Telesto changed their ports to 45678 somewhat recently. The triggernometry xml has 51323 hardcoded in. Ill change it quick and let you know if it works

So i managed to get telesto to respond be changing all the localhost ports in the xml and within triggernometry.
For the auto refreshing of food and such do I need to add that myself to the macros or is that something triggernometry is meant to be doing by itself

**Comment by hikarin-dev** [comment]
That's great that you found the issue and a solution! :)

And unfortunately, it's not something the trigger can do at the moment, the timing required to exit the "synthesizing state" to use an item is too dependent on the latency. I figure I can just spam trying, but since there's no way for the trigger to automate selecting nq/hq materials anyway to restart the loop, I've decided to not implement food/pot refresh at all.

I recommend just using the artisan plugin (repo link: `https://love.puni.sh/ment.json`), as it does exactly what you're looking for and more, and just use this trigger again if that plugin ever stops getting support.

I'm only recommending this trigger now for those that are still on the fence about the use of Dalamud plugins and are scared of getting detected and banned, as it can be argued that what this trigger is doing is only pressing 2 keys at a specific timing that is based on the log lines it can read, just slightly neater than most mech keyboard with a macro loop feature.

**Comment by 3r022** [comment]
Thanks again for the help, I really appreciate it. Ill have a lock at that repo, but thanks for making this macro it definitely gets the job done :)

**Comment by hikarin-dev** [comment]
For now, I'll just write what the port the macro is using, as updating it with their new default port could break other's old setup, and the user can either configure the xml or telesto to whatever suits their use.
